pkg/sql/colexec/auto_incr.go
=> modify new delete function in auto_incr

pkg/sql/plan/build_constraint_util.go, pkg/sql/plan/mock.go
=> add mock test

pkg/sql/plan/build_constraint_util.go
issue #6597
Fix the composite primary key bug
=> modify Composite primary key bug

pkg/sql/plan/build_constraint_util.go
=> add update columns map code

test/distributed/cases/foreign_key/fk_base.result, test/distributed/cases/foreign_key/fk_base.sql
issue #6597
add foreign key bvt test
=> add foreign keybvt test

pkg/sql/colexec/deletion/deletion.go, pkg/sql/colexec/deletion/types.go, pkg/sql/colexec/insert/types.go, pkg/sql/colexec/mergeblock/mergeblock_test.go, pkg/sql/colexec/mergeblock/types.go, pkg/sql/colexec/update/types.go, pkg/sql/colexec/update/update.go, pkg/sql/compile/compile.go, pkg/sql/compile/dml.go, pkg/vm/types.go
issue #
Add AffectedRows interface.
=> Add AffectedRows interface.

pkg/sql/colexec/deletion/deletion.go
=> Copy original batch after delete operator.

pkg/sql/compile/debugTools.go, pkg/sql/compile/scopeRemoteRun.go, pkg/sql/compile/types.go, pkg/vm/types.go
=> Add op type and magic type

pkg/sql/colexec/mergeblock/mergeblock.go, pkg/sql/colexec/mergeblock/mergeblock_test.go, pkg/sql/colexec/mergeblock/types.go
=> Fix mergeblock bug new

pkg/sql/compile/compile.go
=> fix data race

pkg/sql/colexec/mergeblock/mergeblock.go, pkg/sql/colexec/mergeblock/types.go
=> Fix memleak for mergeblock new

pkg/sql/colexec/insert/insert.go, pkg/sql/colexec/s3util.go
=> fix memory leak

pkg/frontend/test/txn_mock.go, pkg/sql/colexec/lockop/lock_op.go, pkg/txn/client/client.go, pkg/txn/client/operator.go, pkg/txn/client/operator_test.go, pkg/txn/client/types.go, pkg/txn/storage/memorystorage/storage_txn_client.go, pkg/vm/engine/entire_engine_test.go
=> txn: add update snapshot ts

pkg/sql/compile/compile.go, pkg/sql/compile/ddl.go
=> Refactor ddl remove the hack

pkg/container/batch/batch.go, pkg/vm/engine/disttae/txn_table.go
=> Remove batch append

pkg/sql/colexec/right/join.go, pkg/sql/colexec/right/types.go
=> Fix the bug of right join

pkg/incrservice/store_sql.go
=> Fix the sca of incservice

pkg/container/types/bytes.go, pkg/container/vector/vector.go
=> small improve

pkg/util/export/etl/db/db_holder.go, pkg/util/export/etl/db/db_holder_test.go, pkg/util/export/etl/sql.go
=> Using prepare in bulkInsert

pkg/frontend/test/txn_mock.go, pkg/sql/colexec/evalExpression_test.go, pkg/sql/colexec/rightanti/join_test.go, pkg/sql/plan/function/function_test.go
=> Fix the bug of windown
